services:
  server:
    image: server:latest
    pull_policy: always
    build:
      context: ../..
      dockerfile: ../../Dockerfile
    command:
      - --logging.config=/app/data-volume/logback-test.xml
    ports:
      - "8084:8081"
    volumes:
      - ./data-volume:/app/data-volume

  client:
    image: dtatout:latest
    depends_on:
      - server
    build:
      context: /home/user/RustroverProjects/dataout
      dockerfile: /home/user/RustroverProjects/dataout/Dockerfile
